// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: meal_suggest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

fileprivate struct _GeneratedWithProtocGenSwiftVersion_MealSuggest: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Eater_MealSuggestRequest: Sendable {
  var days: Int32 = 0

  /// ISO 639-1 (e.g. pl, uk). Suggestion text in this language.
  var languageCode: String = String()

  /// 0-based; another idea from the same history
  var variant: Int32 = 0

  var remainingKcal: Int32 = 0

  var remainingProtein: Double = 0

  var remainingCarbs: Double = 0

  var remainingFats: Double = 0

  var remainingSugar: Double = 0

  var mealsToday: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Eater_MealSuggestDish: Sendable {
  var name: String = String()

  var why: String = String()

  var basedOn: String = String()

  var howTo: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Eater_MealSuggestResponse: Sendable {
  var text: String = String()

  var dish: Eater_MealSuggestDish {
    get { _dish ?? Eater_MealSuggestDish() }
    set { _dish = newValue }
  }
  var hasDish: Bool { self._dish != nil }
  mutating func clearDish() { self._dish = nil }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _dish: Eater_MealSuggestDish? = nil
}

fileprivate let _protobuf_package_meal_suggest = "eater"

extension Eater_MealSuggestRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package_meal_suggest + ".MealSuggestRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}days\0\u{3}language_code\0\u{1}variant\0\u{3}remaining_kcal\0\u{3}remaining_protein\0\u{3}remaining_carbs\0\u{3}remaining_fats\0\u{3}remaining_sugar\0\u{3}meals_today\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.days) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.languageCode) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.variant) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.remainingKcal) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.remainingProtein) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.remainingCarbs) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self.remainingFats) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self.remainingSugar) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.mealsToday) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.days != 0 {
      try visitor.visitSingularInt32Field(value: self.days, fieldNumber: 1)
    }
    if !self.languageCode.isEmpty {
      try visitor.visitSingularStringField(value: self.languageCode, fieldNumber: 2)
    }
    if self.variant != 0 {
      try visitor.visitSingularInt32Field(value: self.variant, fieldNumber: 3)
    }
    if self.remainingKcal != 0 {
      try visitor.visitSingularInt32Field(value: self.remainingKcal, fieldNumber: 4)
    }
    if self.remainingProtein.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.remainingProtein, fieldNumber: 5)
    }
    if self.remainingCarbs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.remainingCarbs, fieldNumber: 6)
    }
    if self.remainingFats.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.remainingFats, fieldNumber: 7)
    }
    if self.remainingSugar.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.remainingSugar, fieldNumber: 8)
    }
    if self.mealsToday != 0 {
      try visitor.visitSingularInt32Field(value: self.mealsToday, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Eater_MealSuggestRequest, rhs: Eater_MealSuggestRequest) -> Bool {
    if lhs.days != rhs.days { return false }
    if lhs.languageCode != rhs.languageCode { return false }
    if lhs.variant != rhs.variant { return false }
    if lhs.remainingKcal != rhs.remainingKcal { return false }
    if lhs.remainingProtein != rhs.remainingProtein { return false }
    if lhs.remainingCarbs != rhs.remainingCarbs { return false }
    if lhs.remainingFats != rhs.remainingFats { return false }
    if lhs.remainingSugar != rhs.remainingSugar { return false }
    if lhs.mealsToday != rhs.mealsToday { return false }
    if lhs.unknownFields != rhs.unknownFields { return false }
    return true
  }
}

extension Eater_MealSuggestDish: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package_meal_suggest + ".MealSuggestDish"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}why\0\u{3}based_on\0\u{3}how_to\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.why) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.basedOn) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.howTo) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.why.isEmpty {
      try visitor.visitSingularStringField(value: self.why, fieldNumber: 2)
    }
    if !self.basedOn.isEmpty {
      try visitor.visitSingularStringField(value: self.basedOn, fieldNumber: 3)
    }
    if !self.howTo.isEmpty {
      try visitor.visitSingularStringField(value: self.howTo, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Eater_MealSuggestDish, rhs: Eater_MealSuggestDish) -> Bool {
    if lhs.name != rhs.name { return false }
    if lhs.why != rhs.why { return false }
    if lhs.basedOn != rhs.basedOn { return false }
    if lhs.howTo != rhs.howTo { return false }
    if lhs.unknownFields != rhs.unknownFields { return false }
    return true
  }
}

extension Eater_MealSuggestResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package_meal_suggest + ".MealSuggestResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{1}dish\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._dish) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 1)
    }
    try { if let v = self._dish {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Eater_MealSuggestResponse, rhs: Eater_MealSuggestResponse) -> Bool {
    if lhs.text != rhs.text { return false }
    if lhs._dish != rhs._dish { return false }
    if lhs.unknownFields != rhs.unknownFields { return false }
    return true
  }
}
