// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Services/modify_food_record.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

struct Eater_ModifyFoodRecordRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var time: Int64 = 0

    var userEmail: String = .init()

    var percentage: Int32 = 0

    var isTryManually: Bool = false

    var manualFoodName: String = .init()

    var manualInsight: String = .init()

    var manualComponents: [String] = []

    var imageID: String = .init()

    var addedSugarTsp: Float = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

struct Eater_ModifyFoodRecordResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var success: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "Eater"

extension Eater_ModifyFoodRecordRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ModifyFoodRecordRequest"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "time"),
        2: .standard(proto: "user_email"),
        3: .same(proto: "percentage"),
        4: .standard(proto: "is_try_manually"),
        5: .standard(proto: "manual_food_name"),
        6: .standard(proto: "manual_insight"),
        7: .standard(proto: "manual_components"),
        8: .standard(proto: "image_id"),
        9: .standard(proto: "added_sugar_tsp"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularInt64Field(value: &time)
            case 2: try decoder.decodeSingularStringField(value: &userEmail)
            case 3: try decoder.decodeSingularInt32Field(value: &percentage)
            case 4: try decoder.decodeSingularBoolField(value: &isTryManually)
            case 5: try decoder.decodeSingularStringField(value: &manualFoodName)
            case 6: try decoder.decodeSingularStringField(value: &manualInsight)
            case 7: try decoder.decodeRepeatedStringField(value: &manualComponents)
            case 8: try decoder.decodeSingularStringField(value: &imageID)
            case 9: try decoder.decodeSingularFloatField(value: &addedSugarTsp)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if time != 0 {
            try visitor.visitSingularInt64Field(value: time, fieldNumber: 1)
        }
        if !userEmail.isEmpty {
            try visitor.visitSingularStringField(value: userEmail, fieldNumber: 2)
        }
        if percentage != 0 {
            try visitor.visitSingularInt32Field(value: percentage, fieldNumber: 3)
        }
        if isTryManually != false {
            try visitor.visitSingularBoolField(value: isTryManually, fieldNumber: 4)
        }
        if !manualFoodName.isEmpty {
            try visitor.visitSingularStringField(value: manualFoodName, fieldNumber: 5)
        }
        if !manualInsight.isEmpty {
            try visitor.visitSingularStringField(value: manualInsight, fieldNumber: 6)
        }
        if !manualComponents.isEmpty {
            try visitor.visitRepeatedStringField(value: manualComponents, fieldNumber: 7)
        }
        if !imageID.isEmpty {
            try visitor.visitSingularStringField(value: imageID, fieldNumber: 8)
        }
        if addedSugarTsp != 0 {
            try visitor.visitSingularFloatField(value: addedSugarTsp, fieldNumber: 9)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Eater_ModifyFoodRecordRequest, rhs: Eater_ModifyFoodRecordRequest) -> Bool {
        if lhs.time != rhs.time { return false }
        if lhs.userEmail != rhs.userEmail { return false }
        if lhs.percentage != rhs.percentage { return false }
        if lhs.isTryManually != rhs.isTryManually { return false }
        if lhs.manualFoodName != rhs.manualFoodName { return false }
        if lhs.manualInsight != rhs.manualInsight { return false }
        if lhs.manualComponents != rhs.manualComponents { return false }
        if lhs.imageID != rhs.imageID { return false }
        if lhs.addedSugarTsp != rhs.addedSugarTsp { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Eater_ModifyFoodRecordResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ModifyFoodRecordResponse"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "success"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularBoolField(value: &success)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if success != false {
            try visitor.visitSingularBoolField(value: success, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Eater_ModifyFoodRecordResponse, rhs: Eater_ModifyFoodRecordResponse) -> Bool {
        if lhs.success != rhs.success { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
