// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: modify_food_record.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Eater_ModifyFoodRecordRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var time: Int64 = 0

  var userEmail: String = String()

  var percentage: Int32 = 0

  var isTryManually: Bool = false

  var manualFoodName: String = String()

  var manualInsight: String = String()

  var manualComponents: [String] = []

  /// for try-again: MinIO path to re-trigger analysis
  var imageID: String = String()

  /// Added sugar in teaspoons (1 tsp = ~5g, ~20 cal)
  var addedSugarTsp: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Eater_ModifyFoodRecordResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var success: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "Eater"

extension Eater_ModifyFoodRecordRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ModifyFoodRecordRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}time\0\u{3}user_email\0\u{1}percentage\0\u{3}is_try_manually\0\u{3}manual_food_name\0\u{3}manual_insight\0\u{3}manual_components\0\u{3}image_id\0\u{3}added_sugar_tsp\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.time) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.userEmail) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.percentage) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isTryManually) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.manualFoodName) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.manualInsight) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.manualComponents) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.imageID) }()
      case 9: try { try decoder.decodeSingularFloatField(value: &self.addedSugarTsp) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.time != 0 {
      try visitor.visitSingularInt64Field(value: self.time, fieldNumber: 1)
    }
    if !self.userEmail.isEmpty {
      try visitor.visitSingularStringField(value: self.userEmail, fieldNumber: 2)
    }
    if self.percentage != 0 {
      try visitor.visitSingularInt32Field(value: self.percentage, fieldNumber: 3)
    }
    if self.isTryManually != false {
      try visitor.visitSingularBoolField(value: self.isTryManually, fieldNumber: 4)
    }
    if !self.manualFoodName.isEmpty {
      try visitor.visitSingularStringField(value: self.manualFoodName, fieldNumber: 5)
    }
    if !self.manualInsight.isEmpty {
      try visitor.visitSingularStringField(value: self.manualInsight, fieldNumber: 6)
    }
    if !self.manualComponents.isEmpty {
      try visitor.visitRepeatedStringField(value: self.manualComponents, fieldNumber: 7)
    }
    if !self.imageID.isEmpty {
      try visitor.visitSingularStringField(value: self.imageID, fieldNumber: 8)
    }
    if self.addedSugarTsp.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.addedSugarTsp, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Eater_ModifyFoodRecordRequest, rhs: Eater_ModifyFoodRecordRequest) -> Bool {
    if lhs.time != rhs.time {return false}
    if lhs.userEmail != rhs.userEmail {return false}
    if lhs.percentage != rhs.percentage {return false}
    if lhs.isTryManually != rhs.isTryManually {return false}
    if lhs.manualFoodName != rhs.manualFoodName {return false}
    if lhs.manualInsight != rhs.manualInsight {return false}
    if lhs.manualComponents != rhs.manualComponents {return false}
    if lhs.imageID != rhs.imageID {return false}
    if lhs.addedSugarTsp != rhs.addedSugarTsp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Eater_ModifyFoodRecordResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ModifyFoodRecordResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Eater_ModifyFoodRecordResponse, rhs: Eater_ModifyFoodRecordResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
