// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: statistics_range.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Eater_GetStatisticsRangeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// dd-mm-yyyy
  var startDate: String = String()

  /// dd-mm-yyyy
  var endDate: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Eater_DayStatistics: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// dd-mm-yyyy
  var date: String = String()

  var totalCalories: Int32 = 0

  var totalAvgWeight: Int32 = 0

  var proteins: Double = 0

  var fats: Double = 0

  var carbohydrates: Double = 0

  var sugar: Double = 0

  var numberOfMeals: Int32 = 0

  /// 0 = nothing rated that day
  var avgHealthScore: Int32 = 0

  var personWeight: Float = 0

  var hasData_p: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Eater_GetStatisticsRangeResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var days: [Eater_DayStatistics] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "eater"

extension Eater_GetStatisticsRangeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetStatisticsRangeRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_date\0\u{3}end_date\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.startDate) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.endDate) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.startDate.isEmpty {
      try visitor.visitSingularStringField(value: self.startDate, fieldNumber: 1)
    }
    if !self.endDate.isEmpty {
      try visitor.visitSingularStringField(value: self.endDate, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Eater_GetStatisticsRangeRequest, rhs: Eater_GetStatisticsRangeRequest) -> Bool {
    if lhs.startDate != rhs.startDate {return false}
    if lhs.endDate != rhs.endDate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Eater_DayStatistics: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DayStatistics"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}date\0\u{3}total_calories\0\u{3}total_avg_weight\0\u{1}proteins\0\u{1}fats\0\u{1}carbohydrates\0\u{1}sugar\0\u{3}number_of_meals\0\u{3}avg_health_score\0\u{3}person_weight\0\u{3}has_data\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.date) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.totalCalories) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.totalAvgWeight) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.proteins) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.fats) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.carbohydrates) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self.sugar) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.numberOfMeals) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.avgHealthScore) }()
      case 10: try { try decoder.decodeSingularFloatField(value: &self.personWeight) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self.hasData_p) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.date.isEmpty {
      try visitor.visitSingularStringField(value: self.date, fieldNumber: 1)
    }
    if self.totalCalories != 0 {
      try visitor.visitSingularInt32Field(value: self.totalCalories, fieldNumber: 2)
    }
    if self.totalAvgWeight != 0 {
      try visitor.visitSingularInt32Field(value: self.totalAvgWeight, fieldNumber: 3)
    }
    if self.proteins.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.proteins, fieldNumber: 4)
    }
    if self.fats.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.fats, fieldNumber: 5)
    }
    if self.carbohydrates.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.carbohydrates, fieldNumber: 6)
    }
    if self.sugar.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.sugar, fieldNumber: 7)
    }
    if self.numberOfMeals != 0 {
      try visitor.visitSingularInt32Field(value: self.numberOfMeals, fieldNumber: 8)
    }
    if self.avgHealthScore != 0 {
      try visitor.visitSingularInt32Field(value: self.avgHealthScore, fieldNumber: 9)
    }
    if self.personWeight.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.personWeight, fieldNumber: 10)
    }
    if self.hasData_p != false {
      try visitor.visitSingularBoolField(value: self.hasData_p, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Eater_DayStatistics, rhs: Eater_DayStatistics) -> Bool {
    if lhs.date != rhs.date {return false}
    if lhs.totalCalories != rhs.totalCalories {return false}
    if lhs.totalAvgWeight != rhs.totalAvgWeight {return false}
    if lhs.proteins != rhs.proteins {return false}
    if lhs.fats != rhs.fats {return false}
    if lhs.carbohydrates != rhs.carbohydrates {return false}
    if lhs.sugar != rhs.sugar {return false}
    if lhs.numberOfMeals != rhs.numberOfMeals {return false}
    if lhs.avgHealthScore != rhs.avgHealthScore {return false}
    if lhs.personWeight != rhs.personWeight {return false}
    if lhs.hasData_p != rhs.hasData_p {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Eater_GetStatisticsRangeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetStatisticsRangeResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}days\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.days) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.days.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.days, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Eater_GetStatisticsRangeResponse, rhs: Eater_GetStatisticsRangeResponse) -> Bool {
    if lhs.days != rhs.days {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
